name: CI

on:
  push:
    branches: [ '**' ]
    tags: [v*]
  pull_request:
    branches: [ '**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v5
      - name: Run tests
        run: ./mill _.test

      - name: Setup GPG secrets for publish
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v'))
        run: |
          gpg --version
          cat <(echo "${{ secrets.GPG_SECRET_KEY }}") | base64 --decode | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Publish to Maven Central
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/v'))
        run: ./mill -i mill.scalalib.PublishModule/publishAll --publishArtifacts __.publishArtifacts --sonatypeCreds '${{ secrets.SONATYPE_CREDS }}' --gpgArgs "--batch,--yes,-a,-b" --release true
